FROM node:latest

# # Create project directory
# WORKDIR /var/www/project

# COPY . ./
# COPY package*.json ./

RUN apt-get update && apt-get install yarn -y

# EXPOSE 3000
# CMD [ "node", "server.js" ]